---
title: "Forecasting Average Incomes by Industry for Each Province in China (ARIMA Model)"
output: 
    flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r,echo=FALSE}

library(forecast)
library(scales)
library(dygraphs)
library(tidyverse)
library(shiny)
library(plotly)
library(zoo)

# Set file reading path
file_paths <- list.files(
  path="C:/Users/Administrator/Desktop/New folder/New folder", 
  pattern="\\.csv$", full.names=TRUE
  )

# Read files and store them in a list
data_list <- lapply(file_paths, read.csv)

# Rename data names within each list
names(data_list) <- c(
  "ALL","2013", "2014", "2015", "2016", "2017", 
  "2018", "2019", "2020", "2021", "2022"
  )
# Correct data errors，but now directly modify the original data
# data_list[['2021']][16,"Construction"] <- 58683

# Remove excess data
data_list<- data_list[-1]

# Set labels for provinces and industries options
selet_region <- data_list[['2013']]$Region
selet_sectors <- colnames(data_list[['2013']][-c(1:2)])


```


```{r}
# Remove columns with mean values from the data and reshape the data into long format

for(n in names(data_list))
{
data_list[[n]] <- data_list[[n]][-2]
data_list[[n]] <- data_list[[n]] %>%
  pivot_longer(
    cols = starts_with(colnames(data_list[[n]])[-1]),
    names_to = "Sectors",
    values_to = "Wage"
  )
}
```
 
```{r}
# Combine data from a list into a single data frame

combined_data <- do.call(rbind, data_list)
year_info <- rep(2013:2022, each = nrow(data_list[[1]]))
combined_data <- cbind(Year = year_info, combined_data)

```

```{r}
# reshape data to wide format

combined_data_wide <- combined_data %>%
  pivot_wider(
    names_from = c(Region, Sectors),   # Combine province and industry as column names
    values_from = Wage,                # Columns containing values
    names_sep = "_"                    # Column name delimiter
  )

```

 
Column {.sidebar}
-------------------------------------
    
<h3 style="font-size: 17px;font-weight: bold; color: red;">Select the provinces and industries for prediction</h3>
    
```{r}
# 
      selectInput(
        'e0', 'Pronvince', choices = selet_region,
        selectize = FALSE
      )
      selectInput(
        'e1', 'Sectors', choices = selet_sectors,
        selectize = FALSE
      )
  
```
 
<h3 style="font-size: 17px;font-weight: bold; color: red;">Select the parameters for prediction</h3>
 
```{r}
#
      sliderInput("p", HTML("<strong>p-value:</strong>"),
                  min = 0, max = 4,
                  value = 2,)
      sliderInput("d", HTML("<strong>d-value:</strong>"),
                  min = 0, max = 4,
                  value = 2)
      sliderInput("q", HTML("<strong>q-value:</strong>"),
                  min = 0, max = 5,
                  value = 2)
      
```

  
Column {.tabset}
-------------------------------------
   
### ARIMA Model

```{r}


renderPlotly({
  
  # Fit ARIMA model to the selected data and make predictions for ten years ahead
  column_name <- paste(input$e0, input$e1, sep = "_")  
  fit <- arima(combined_data_wide[[column_name]],order=c(input$p,input$d,input$q))
  forecast_values <- forecast(fit, h=10)
  
  # Extract confidence interval data
  data_upper <- as.data.frame(forecast_values$upper)
  data_lower <- as.data.frame(forecast_values$lower)
  
  colnames(data_upper) <- c("upper80", "upper95")
  colnames(data_lower) <- c("lower80", "lower95")
  
  data_interval <- cbind(data_upper, data_lower)
  
  data_interval <- cbind(Years = c(2023:2032), data_interval)

# Adding Time Column and Separating Historical Data and Forecast Data
  empty_ts <- c(as.vector(forecast_values$x),as.vector(forecast_values$mean))
  empty_ts <- data.frame(empty_ts)
  colnames(empty_ts)[colnames(empty_ts) == "empty_ts"] <- "Income"
  row.names(empty_ts) <- c(2013:2032)
  empty_ts <- cbind(Years = c(2013:2032), empty_ts)
  data.2022 <- empty_ts[1:10,]
  data.2032 <- empty_ts[(nrow(empty_ts) - 10):nrow(empty_ts), ]
  
  data_interval <- merge(empty_ts, data_interval, by = "Years", all.x = TRUE)
  
# Creating Forecasting Graphs
  p <- ggplot(empty_ts,aes(x=Years, y=Income)) +
                                    geom_line(data = data.2022,color="blue") + 
                                    geom_line(data = data.2032,color="red") +
                                    scale_y_continuous(labels = scales::comma)+
                                    scale_x_continuous(breaks = c(2013:2032),) +  # etting the Tick Positions
                                    scale_y_continuous(breaks = seq(0,700000,by = 20000)) +  
                                    scale_color_manual(values = c("gray", "red"), guide = FALSE) +
                                    theme_classic(base_size = 20) +
                                    geom_ribbon(data = data_interval, aes(
                                      x = Years, ymin = lower80, 
                                      ymax = upper80), 
                                      fill = "blue",alpha = 0.2) +   # Plotting Confidence Intervals
                                    geom_ribbon(data = data_interval, aes(
                                      x = Years, ymin = lower95, 
                                      ymax = upper95), fill = "blue",alpha = 0.5) +  # Plotting Confidence Intervals
                                    labs(x = "Years",y = "Average income")
# Creating Interactive Graphics  
  ggplotly(p)
})

```   
 
### ACF 
    
```{r}

# Plotting the ACF Chart
renderPlot({
   column_name <- paste(input$e0, input$e1, sep = "_") 
   combined_data_wide[[column_name]]
   acf_result <- acf(diff(combined_data_wide[[column_name]],lag =1), lag.max = 20,main = "Autocorrelation Function (PACF) Plot")  
   
   

  
    
})

```


### PACF
    
```{r}

# Plotting the PACF Chart

renderPlot({
   column_name <- paste(input$e0, input$e1, sep = "_") 
   combined_data_wide[[column_name]]
   acf_result <- pacf(diff(combined_data_wide[[column_name]],lag =1), lag.max = 20,main = "Partial Autocorrelation Function (PACF) Plot")  
})

```